var topMovie1 =['1: coco ', 'Miguel '];
var topMovie2 =['2: instructions not included ', 'Valentin '];
var topMovie3 = [ '3: spiderman ', 'peter '];
var topMovie4 = ['4: avengers ', 'too many to name '];
var topMovie5 = ['5: fast and furious ', 'bryan '];
var topMovies = [];
var topMoviestitles = [];
topMovies.push(topMovie1, topMovie2, topMovie3, topMovie4, topMovie5);
topMoviestitles.push(topMovies[0][0], topMovies[1][0], topMovies[2][0], topMovies[3][0], topMovies[4][0], );
alert(topMoviestitles);
var favAndleastFav =[];
favAndleastFav.push(topMovie1[0], topMovie5[0]);
console.log("favorit and least " + favAndleastFav);
alert(topMovies.length);
